### ISSUE TITLE
help help

### ISSUE THREAD

**Issue by NoObcOderRRRR** [rsamf/kdd-cup-23#2]
hey can you help me a bit.this is my university assignment and i dont know hell about dl.i just know basic rnns but can't find a main.py file in ur code to run baseline rnn. ihave no idea what other files are.can you help pls urgently.also to run baseline rnn ill need baseline rnn .py and data.py only na apart from a main.py file.but where is that

**Comment by rsamf** [comment]
Sorry, I cannot help you with your assignment. Please read the new README that I have added to the repo. Additionally, this repo is not meant to be a demonstrable walkthrough of deep learning and RNN's. However, I would recommend finding some resources on YouTube and the KDD Cup notebooks as a starter.
